export const APP_PAGE_ID = 'APP_ID';

export const FORM_NAMES = {
  LOGIN: 'LOGIN_FORM',
  SINGUP: 'SINGUP_FORM',
  SETTINGS_UPDATE_PASSWORD: 'SETTINGS_UPDATE_PASSWORD_FORM',
};

export const COOKIE_AUTH = 'COOKIE_AUTH_APP';

export const OBSERVE_INTERVAL = {
  ACCOUNT_BALANCE: 1000 * 60 * 3,
  ACCOUNT_PAYMENT_HISTORY: 1000 * 60 * 3,
  ACCOUNT_SHOP_PURCHASE_HISTORY: 1000 * 60 * 3,
  PAGINATION_REQUEST: 500,
};
