export const PAGE_TYPE = {
  HOME: 'HOME',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  ERROR: 'ERROR',
  SIGNUP: 'SIGNUP',
  NOT_FOUND: 'NOT_FOUND',
  ACCESS_DENIED: 'ACCESS_DENIED',
  SERVER_ERROR: 'SERVER_ERROR',
  PAYMENT: 'PAYMENT',
};
